version: '3'

services:
  frontend:
    build:
      context: ./ttpjc
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Map port 8081 on host to port 8081 in the container
    volumes:
      - ./ttpjc:/app
      - /app/node_modules

  backend:
    build:
      context: ./ttpjcbe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ttpjcbe:/app
      - /app/node_modules
